
# GPS

GPS_GOOD_ACCURACY=10
GPS_WARNING_ACCURACY=30
GPS_BAD_ACCURACY=50

GPS_JUMP_METERS=100

# NETWORK

PING_GOOD=50
PING_WARNING=120
PING_BAD=250

NETWORK_TIMEOUT=5

# BATTERY

BATTERY_LOW=20

# TEMPERATURE

TEMP_WARNING=42
TEMP_HIGH=48
TEMP_CRITICAL=55
